"use server"
import { and, asc, between, desc, eq, inArray } from "drizzle-orm"
import { revalidatePath } from "next/cache"
import { z } from "zod"
import { db } from "@/lib/db"
import { auditLogs, rates, trips } from "@/lib/db/schema"
import { extractedTripSchema, tripKindOf, type ExtractedTrip } from "@/lib/domain"
import { requireOwner } from "@/lib/tenant"

export async function getRates() { const t = await requireOwner(); return db.select().from(rates).where(eq(rates.organizationId, t.organizationId)).orderBy(asc(rates.company), asc(rates.direction), asc(rates.tripKind)) }
export async function updateRate(id: number, newRate: number) { const t = await requireOwner(); const rate = z.number().int().positive().max(1_000_000).parse(newRate); await db.transaction(async tx => { const [row] = await tx.update(rates).set({ rate }).where(and(eq(rates.id, id), eq(rates.organizationId, t.organizationId))).returning({ id: rates.id }); if (!row) throw new Error("Rate not found"); await tx.insert(auditLogs).values({ organizationId: t.organizationId, actorUserId: t.user.id, action: "rate.updated", entityType: "rate", entityId: String(id) }) }); revalidatePath("/settings") }
async function rateFor(org: string, company: string, direction: string, size: string, tripType: string) { const [row] = await db.select().from(rates).where(and(eq(rates.organizationId, org), eq(rates.company, company), eq(rates.direction, direction), eq(rates.tripKind, tripKindOf(size, tripType)))).limit(1); if (!row) throw new Error("No matching rate configured"); return row.rate }
export async function findDuplicates(entries: Array<{ tripDate: string; containerNo: string }>) { const t = await requireOwner(); if (!entries.length) return []; const existing = await db.select({ tripDate: trips.tripDate, containerNo: trips.containerNo }).from(trips).where(and(eq(trips.organizationId, t.organizationId), inArray(trips.containerNo, [...new Set(entries.map(e => e.containerNo))]))); const set = new Set(existing.map(e => `${e.tripDate}|${e.containerNo}`)); return entries.filter(e => set.has(`${e.tripDate}|${e.containerNo}`)) }
export interface SaveTripsResult { saved: number; skippedDuplicates: number; errors: string[] }
export async function saveTrips(rawEntries: ExtractedTrip[]): Promise<SaveTripsResult> { const tenant = await requireOwner(); const errors: string[] = []; let saved = 0, skippedDuplicates = 0; for (const raw of rawEntries) { const parsed = extractedTripSchema.safeParse(raw); if (!parsed.success) { errors.push(`${raw.containerNo ?? "?"}: invalid data`); continue } const t = parsed.data; try { const rate = await rateFor(tenant.organizationId, t.company, t.direction, t.size, t.tripType); const inserted = await db.insert(trips).values({ organizationId: tenant.organizationId, tripDate: t.tripDate, containerNo: t.containerNo, size: t.size, tripType: t.tripType, containerNo2: t.containerNo2 ?? null, fromLocation: t.fromLocation, toLocation: t.toLocation, company: t.company, direction: t.direction, rate }).onConflictDoNothing({ target: [trips.organizationId, trips.tripDate, trips.containerNo] }).returning({ id: trips.id }); inserted.length ? saved++ : skippedDuplicates++ } catch (e) { errors.push(`${t.containerNo}: ${e instanceof Error ? e.message : "unknown error"}`) } } if (saved) await db.insert(auditLogs).values({ organizationId: tenant.organizationId, actorUserId: tenant.user.id, action: "trips.created", entityType: "trip", metadata: { count: saved } }); revalidatePath("/trips"); revalidatePath("/"); return { saved, skippedDuplicates, errors } }
export async function getTrips(from?: string, to?: string) { const t = await requireOwner(); const filter = from && to ? and(eq(trips.organizationId, t.organizationId), between(trips.tripDate, from, to)) : eq(trips.organizationId, t.organizationId); return db.select().from(trips).where(filter).orderBy(desc(trips.tripDate), desc(trips.id)).limit(300) }
const updateSchema = extractedTripSchema.extend({ containerNo2: z.string().nullable() })
export async function updateTrip(id: number, data: z.infer<typeof updateSchema>) { const tenant = await requireOwner(); const t = updateSchema.parse(data); const rate = await rateFor(tenant.organizationId, t.company, t.direction, t.size, t.tripType); const [row] = await db.update(trips).set({ ...t, containerNo: t.containerNo.toUpperCase(), fromLocation: t.fromLocation.toUpperCase(), toLocation: t.toLocation.toUpperCase(), rate, updatedAt: new Date() }).where(and(eq(trips.id, id), eq(trips.organizationId, tenant.organizationId))).returning({ id: trips.id }); if (!row) throw new Error("Trip not found"); revalidatePath("/trips"); revalidatePath("/") }
export async function deleteTrip(id: number) { const t = await requireOwner(); const [row] = await db.delete(trips).where(and(eq(trips.id, id), eq(trips.organizationId, t.organizationId))).returning({ id: trips.id }); if (!row) throw new Error("Trip not found"); await db.insert(auditLogs).values({ organizationId: t.organizationId, actorUserId: t.user.id, action: "trip.deleted", entityType: "trip", entityId: String(id) }); revalidatePath("/trips"); revalidatePath("/") }
